import { createExtendedExamples } from './extended-curve-examples';

export interface CurveExample {
  id: string;
  name: string;
  category: string;
  description: string;
  formula: string;
  bounds: [number, number, number, number];
  source?: string;
  kind?: 'Clásica' | 'Variante' | 'Composición';
  family?: string;
}

export const FEATURED_EXAMPLE_IDS = new Set([
  'heart', 'butterfly', 'rose12', 'lotus', 'snowflake', 'galaxy', 'counter-spirals',
  'two-sources', 'quasicrystal', 'moire', 'lissajous57', 'mandala-lotus',
  'mandala-pearl', 'coral', 'fingerprint', 'topography',
  'bicorn', 'nephroid', 'deltoid', 'ampersand', 'bean', 'butterfly-algebraic',
  'gielis-6-petalo', 'multifocal-5-estrella'
]);

function example(id: string, name: string, category: string, description: string, formula: string,
  radius = 3, bounds?: CurveExample['bounds']): CurveExample {
  return { id, name, category, description,
    kind: category === 'Clásicas' || ['heart', 'fish', 'bowtie', 'fermat'].includes(id) ? 'Clásica'
      : category === 'Especiales' ? 'Variante' : 'Composición',
    formula: formula.replace(/\br\b/g, 'hypot(x,y)').replace(/\bt\b/g, 'atan2(y,x)'),
    bounds: bounds ?? [-radius, radius, -radius, radius] };
}

/** Visual compositions as well as classical curves; every preset has its own framing.
 * r and t are expanded to Cartesian expressions, so presets remain editable. */
export const CURVE_EXAMPLES: CurveExample[] = [
  example('circle', 'Círculo', 'Clásicas', 'La curva más sencilla: simetría perfecta.', 'x*x+y*y-1', 1.4),
  example('ellipse', 'Elipse', 'Clásicas', 'Óvalo horizontal, ancho y delicado.', 'x*x/4+y*y-1', 2.5),
  example('hyperbola', 'Hipérbola', 'Clásicas', 'Dos ramas que se abren hacia lados opuestos.', 'x*x-y*y-1', 3),
  example('parabola', 'Parábola', 'Clásicas', 'Un arco que crece hacia arriba.', 'y-x*x+1', 2.5),
  example('lemniscate', 'Lemniscata', 'Clásicas', 'Un lazo horizontal con forma de infinito.', '(x*x+y*y)**2-2*(x*x-y*y)', 1.8),
  example('vertical-infinity', 'Infinito vertical', 'Clásicas', 'Una lemniscata que se sostiene en vertical.', '(x*x+y*y)**2-2*(y*y-x*x)', 1.8),
  example('diagonal-infinity', 'Infinito inclinado', 'Clásicas', 'Dos lóbulos enlazados en diagonal.', '(x*x+y*y)**2-4*x*y', 1.8),
  example('cassini', 'Óvalo de Cassini', 'Clásicas', 'Un óvalo estrangulado en el centro.', '((x-1)**2+y*y)*((x+1)**2+y*y)-1.5', 2),
  example('cassini-twins', 'Gemelos de Cassini', 'Clásicas', 'Dos pequeños óvalos separados.', '((x-1)**2+y*y)*((x+1)**2+y*y)-0.5', 1.8),
  example('folium', 'Folium de Descartes', 'Clásicas', 'Un lazo con ramas que escapan en diagonal.', 'x**3+y**3-3*x*y', 3),
  example('witch', 'Bruja de Agnesi', 'Clásicas', 'Una campana racional suave.', 'y*(1+x*x)-1', 3),
  example('catenary', 'Catenaria', 'Clásicas', 'La silueta de una cadena suspendida.', 'y-cosh(x)+1', 2),
  example('astroid', 'Astroide', 'Clásicas', 'Cuatro puntas conectadas por arcos cóncavos.', 'abs(x)**(2/3)+abs(y)**(2/3)-1', 1.4),
  example('superellipse', 'Superelipse', 'Clásicas', 'Un cuadrado de esquinas redondeadas.', 'x**4+y**4-1', 1.4),
  example('diamond', 'Diamante', 'Clásicas', 'Un rombo trazado con valores absolutos.', 'abs(x)+abs(y)-1', 1.4),
  example('squircle', 'Cuadrado inflado', 'Clásicas', 'Entre el círculo y el cuadrado.', 'x*x+y*y-0.8*x*x*y*y-1', 1.4),
  example('heart', 'Corazón', 'Siluetas', 'La clásica silueta de un corazón algebraico.', '(x*x+y*y-1)**3-x*x*y**3', 1.6),
  example('double-heart', 'Dos corazones', 'Siluetas', 'Dos corazones enfrentados, unidos por el encuadre.', '((abs(x)-1.25)**2+y*y-0.65)**3-(abs(x)-1.25)**2*y**3', 2.5),
  example('heart-rings', 'Corazón concéntrico', 'Siluetas', 'Un corazón rodeado por versiones de sí mismo.', 'sin(5*((x*x+y*y-1)**3-x*x*y**3))', 1.55),
  example('egg', 'Huevo', 'Siluetas', 'Un óvalo asimétrico y suave.', 'x*x+(y+0.18*x*x)**2-1', 1.5),
  example('peanut', 'Cacahuete', 'Siluetas', 'Una silueta de dos lóbulos redondeados.', 'r-(1+0.45*cos(2*t))', 1.8),
  example('butterfly', 'Mariposa', 'Siluetas', 'Alas onduladas inspiradas en una curva polar.', 'r-(exp(cos(t))-2*cos(4*t)+0.15*sin(3*t)**5)', 4),
  example('bat', 'Alas nocturnas', 'Siluetas', 'Una composición angular con alas extendidas.', 'r-(1+0.45*cos(2*t)-0.25*cos(4*t)+0.12*cos(8*t))', 2),
  example('fish', 'Pez', 'Siluetas', 'Un cuerpo ovalado y una cola que nace de un cruce.', 'y*y-x*x*(1-x)', 2),
  example('bowtie', 'Pajarita', 'Siluetas', 'Dos lóbulos triangulares con un cruce central.', 'y*y-x*x*(1-x*x)', 1.4),
  example('lens', 'Lente', 'Siluetas', 'Dos arcos forman una lente puntiaguda.', 'max((x-0.65)**2+y*y,(x+0.65)**2+y*y)-1.4', 1.6),
  example('crescent', 'Luna creciente', 'Siluetas', 'Un círculo recortado por otro círculo desplazado.', 'max(x*x+y*y-1,-((x-0.45)**2+y*y-0.85))', 1.4),
  example('yin-yang', 'Doble remolino', 'Siluetas', 'Círculo exterior y dos medias espirales interiores.', '(r-1)*(x-0.32*sin(PI*y))', 1.4),
  example('clover3', 'Trébol de tres hojas', 'Flores', 'Tres pétalos redondos alrededor del centro.', 'r-1-0.55*cos(3*t)', 1.9),
  example('clover4', 'Trébol de cuatro hojas', 'Flores', 'Cuatro hojas amplias y simétricas.', 'r-1-0.55*cos(4*t)', 1.9),
  example('rose3', 'Rosa de tres pétalos', 'Flores', 'Tres pétalos se encuentran en el origen.', 'r-cos(3*t)', 1.3),
  example('rose4', 'Rosa de cuatro pétalos', 'Flores', 'Una rosa polar de cuatro pétalos.', 'r-abs(cos(2*t))', 1.3),
  example('rose5', 'Rosa de cinco pétalos', 'Flores', 'Cinco pétalos con un centro común.', 'r-cos(5*t)', 1.3),
  example('rose8', 'Rosa de ocho pétalos', 'Flores', 'Ocho pétalos finos formando una rueda.', 'r-abs(cos(4*t))', 1.3),
  example('rose12', 'Rosa de doce pétalos', 'Flores', 'Una roseta densa y delicada.', 'r-abs(cos(6*t))', 1.3),
  example('sunflower', 'Girasol', 'Flores', 'Una corona de dieciséis ondulaciones.', 'r-1.15-0.25*cos(16*t)', 1.7),
  example('daisy', 'Margarita', 'Flores', 'Diez pétalos anchos y un disco central.', '(r-1-0.3*cos(10*t))*(r-0.28)', 1.65),
  example('lotus', 'Loto', 'Flores', 'Dos coronas de pétalos superpuestas.', '(r-0.9-0.4*cos(6*t))*(r-0.65-0.2*sin(6*t))', 1.65),
  example('iris', 'Iris', 'Flores', 'Tres pétalos grandes y tres pequeños.', 'r-1-0.45*cos(3*t)-0.15*cos(6*t)', 1.9),
  example('orchid', 'Orquídea', 'Flores', 'Cinco pétalos modulados con ondas secundarias.', 'r-1-0.35*cos(5*t)-0.12*sin(10*t)', 1.8),
  example('petal-weave', 'Pétalos entrelazados', 'Flores', 'Dos rosas giradas que se cruzan.', '(r-abs(cos(4*t)))*(r-abs(sin(4*t)))', 1.3),
  example('flower-rings', 'Flor de agua', 'Flores', 'Tres contornos florales concéntricos.', 'sin(9*(r-0.12*cos(6*t)))', 1.6),
  example('star5', 'Estrella de cinco puntas', 'Estrellas', 'Cinco puntas suaves y profundas.', 'r-1-0.55*cos(5*t)', 1.9),
  example('star6', 'Estrella de seis puntas', 'Estrellas', 'Una estrella de seis brazos.', 'r-1-0.6*cos(6*t)', 1.9),
  example('star8', 'Estrella de ocho puntas', 'Estrellas', 'Ocho brazos largos y estrechos.', 'r-0.7-0.6*abs(cos(4*t))**6', 1.6),
  example('compass', 'Rosa de los vientos', 'Estrellas', 'Cuatro puntas principales y cuatro secundarias.', 'r-0.75-0.4*cos(4*t)-0.2*cos(8*t)', 1.75),
  example('snowflake', 'Copo de nieve', 'Estrellas', 'Seis brazos con pequeñas ramificaciones.', 'r-0.9-0.35*cos(6*t)-0.12*cos(18*t)', 1.7),
  example('gear', 'Engranaje', 'Estrellas', 'Doce dientes y un agujero central.', '(r-1-0.18*cos(12*t))*(r-0.35)', 1.5),
  example('saw-star', 'Estrella afilada', 'Estrellas', 'Un perfil estrellado con puntas de alta curvatura.', 'r-0.55-0.75*abs(cos(5*t))**8', 1.6),
  example('star-shells', 'Estrella estratificada', 'Estrellas', 'Capas concéntricas con ocho puntas.', 'sin(10*r-2*cos(8*t))', 1.65),
  example('spiral', 'Espiral de Arquímedes', 'Espirales', 'Una espiral continua expresada mediante una fase periódica.', 'sin(5*r-t)', 3),
  example('double-spiral', 'Espiral doble', 'Espirales', 'Dos brazos que giran desde el centro.', 'sin(4*r-2*t)', 3),
  example('triple-spiral', 'Espiral triple', 'Espirales', 'Tres brazos en rotación.', 'sin(4*r-3*t)', 3),
  example('galaxy', 'Galaxia', 'Espirales', 'Cinco brazos curvos que se abren hacia el exterior.', 'sin(2.6*r-5*t)', 3.5),
  example('spiral-flower', 'Flor en espiral', 'Espirales', 'Un remolino modulado por seis pétalos.', 'sin(6*r-3*t+0.8*cos(6*t))', 3),
  example('log-spiral', 'Espiral logarítmica', 'Espirales', 'Las vueltas se separan de forma progresiva.', 'sin(5*log(r+0.08)-2*t)', 3),
  example('vortex', 'Vórtice', 'Espirales', 'Las vueltas se comprimen al alejarse del centro.', 'sin(1.8*r*r-3*t)', 3),
  example('counter-spirals', 'Espirales contrapuestas', 'Espirales', 'Dos familias de espirales se entrecruzan.', 'sin(4*r-2*t)*sin(4*r+2*t)', 3),
  example('spiral-ribbon', 'Cinta espiral', 'Espirales', 'Dos bordes paralelos dibujan una cinta curva.', 'cos(5*r-2*t)-0.75', 3),
  example('twisted-flower', 'Flor retorcida', 'Espirales', 'Una flor de ocho lóbulos gira con el radio.', 'r-1-0.4*cos(8*t-4*r)', 1.8),
  example('rings', 'Ondas concéntricas', 'Ondas', 'Anillos circulares como ondas sobre el agua.', 'sin(5*r)', 3),
  example('ripples', 'Ondas apretadas', 'Ondas', 'La separación de los anillos disminuye hacia fuera.', 'sin(2*r*r)', 3),
  example('two-sources', 'Dos fuentes', 'Ondas', 'Interferencia entre dos focos circulares.', 'cos(7*hypot(x-1,y))+cos(7*hypot(x+1,y))', 3),
  example('three-sources', 'Tres fuentes', 'Ondas', 'Una red orgánica creada por tres emisores.', 'cos(6*hypot(x-1,y))+cos(6*hypot(x+0.5,y-0.85))+cos(6*hypot(x+0.5,y+0.85))', 3),
  example('wave-lens', 'Lente de ondas', 'Ondas', 'Óvalos confocales que rodean dos puntos.', 'sin(6*(hypot(x-1,y)+hypot(x+1,y)))', 3),
  example('hyperbolic-waves', 'Ondas hiperbólicas', 'Ondas', 'Abanicos a partir de la diferencia de distancias.', 'sin(8*(hypot(x-1,y)-hypot(x+1,y)))', 3),
  example('standing-wave', 'Onda estacionaria', 'Ondas', 'Una retícula de ondas seno y coseno.', 'sin(3*x)+cos(3*y)', 3),
  example('woven-waves', 'Ondas tejidas', 'Ondas', 'Ondas horizontales y verticales deformadas entre sí.', 'sin(4*x+sin(3*y))+sin(4*y+sin(3*x))', 3),
  example('wave-diamond', 'Diamantes de agua', 'Ondas', 'Anillos angulosos con geometría de Manhattan.', 'sin(5*(abs(x)+abs(y)))', 3),
  example('square-rings', 'Ondas cuadradas', 'Ondas', 'Anillos cuadrados anidados.', 'sin(6*max(abs(x),abs(y)))', 3),
  example('checker-lace', 'Encaje de damero', 'Mosaicos', 'Celdas de curvas cerradas en una cuadrícula.', 'cos(4*x)*cos(4*y)-0.25', 3),
  example('rounded-tiles', 'Baldosas redondeadas', 'Mosaicos', 'Islas curvas repetidas sobre una retícula.', 'cos(3*x)+cos(3*y)-1', 3),
  example('diamond-tiles', 'Mosaico de rombos', 'Mosaicos', 'Una trama diagonal de ondas cruzadas.', 'sin(3*(x+y))*sin(3*(x-y))-0.25', 3),
  example('hex-waves', 'Ondas hexagonales', 'Mosaicos', 'Tres direcciones de ondas producen simetría hexagonal.', 'cos(3*x)+cos(1.5*x+2.598*y)+cos(1.5*x-2.598*y)', 3),
  example('honeycomb', 'Panal ondulado', 'Mosaicos', 'Celdas cerradas de una interferencia triangular.', 'cos(3*x)+cos(1.5*x+2.598*y)+cos(1.5*x-2.598*y)-1.3', 3),
  example('quasicrystal', 'Cuasicristal', 'Mosaicos', 'Cinco direcciones de onda crean una trama de simetría pentagonal.', 'cos(4*x)+cos(4*(0.309*x+0.951*y))+cos(4*(-0.809*x+0.588*y))+cos(4*(-0.809*x-0.588*y))+cos(4*(0.309*x-0.951*y))', 3),
  example('moire', 'Moiré', 'Mosaicos', 'Dos rejillas casi alineadas forman bandas amplias.', 'sin(7*x)*sin(7*y)+sin(7.3*x+0.3*y)*sin(7.3*y-0.3*x)', 3),
  example('warped-grid', 'Retícula flexible', 'Mosaicos', 'Un damero curvado por ondas lentas.', 'sin(4*x+1.2*sin(y))*sin(4*y+1.2*sin(x))-0.15', 3),
  example('bubble-grid', 'Burbujas en fila', 'Mosaicos', 'Pequeños círculos se repiten por toda la ventana.', 'sin(3*x)**2+sin(3*y)**2-0.4', 3),
  example('elliptic-grid', 'Óvalos alternos', 'Mosaicos', 'Un mosaico de óvalos de diferentes orientaciones.', 'sin(3*x)**2+0.55*sin(3*y)**2-0.35', 3),
  example('braid', 'Trenza', 'Tramas', 'Tres hebras oscilantes se cruzan.', '(y-sin(2*x))*(y-sin(2*x+TAU/3))*(y-sin(2*x+2*TAU/3))', 3),
  example('ribbon', 'Cinta sinusoidal', 'Tramas', 'Dos curvas paralelas delimitan una cinta.', '(y-sin(2*x))**2-0.08', 3),
  example('woven-ribbon', 'Cintas cruzadas', 'Tramas', 'Cintas horizontales y verticales forman un tejido.', '((y-sin(2*x))**2-0.05)*((x-sin(2*y))**2-0.05)', 3),
  example('lissajous22', 'Lazos de Chebyshev', 'Tramas', 'Una curva algebraica de aspecto entrelazado.', 'chebyshevT(3,x)-chebyshevT(4,y)', 1.15),
  example('lissajous35', 'Nudo de cinco vueltas', 'Tramas', 'Los polinomios de órdenes 3 y 5 generan lazos.', 'chebyshevT(3,x)-chebyshevT(5,y)', 1.15),
  example('lissajous57', 'Encaje de siete vueltas', 'Tramas', 'Una malla fina de curvas algebraicas.', 'chebyshevT(5,x)-chebyshevT(7,y)', 1.1),
  example('legendre-net', 'Red de Legendre', 'Tramas', 'Dos polinomios generan un entramado ondulado.', 'legendre(6,x)-legendre(6,y)', 1.1),
  example('jacobi-net', 'Tapiz de Jacobi', 'Tramas', 'Una trama asimétrica de polinomios ortogonales.', 'jacobi(5,x,1,2)-jacobi(6,y,2,1)', 1.1),
  example('harmonic-lace', 'Encaje armónico', 'Tramas', 'Un patrón que mezcla ondas de escalas distintas.', 'sin(5*x)*cos(3*y)+sin(3*x)*cos(5*y)', 3),
  example('woven-diagonals', 'Tejido diagonal', 'Tramas', 'Bandas onduladas se cruzan en diagonal.', 'sin(4*(x+y)+sin(x-y))*sin(4*(x-y)+sin(x+y))-0.2', 3),
  example('mandala', 'Mandala', 'Mandalas', 'Anillos y doce radios ondulados.', 'sin(9*r)*cos(6*t)-0.25', 2.4),
  example('mandala-lotus', 'Mandala de loto', 'Mandalas', 'Capas de flores con ocho lóbulos.', 'cos(10*r)+0.65*cos(8*t)', 2.5),
  example('mandala-sun', 'Sol ornamental', 'Mandalas', 'Una trama de círculos y veinticuatro brazos.', 'sin(8*r)+0.4*cos(12*t)', 2.5),
  example('mandala-diamond', 'Mandala de diamantes', 'Mandalas', 'Rombos curvos en una retícula polar.', 'cos(8*r)*cos(8*t)-0.35', 2.5),
  example('mandala-pearl', 'Collar de perlas', 'Mandalas', 'Pequeños óvalos se distribuyen en anillos.', 'sin(7*r)**2+sin(6*t)**2-0.35', 2.5),
  example('mandala-woven', 'Mandala tejido', 'Mandalas', 'Dos ondas polares se cruzan en diagonal.', 'sin(7*r+5*t)*sin(7*r-5*t)-0.2', 2.5),
  example('mandala-eye', 'Ojo radial', 'Mandalas', 'Un centro circular y coronas de pétalos.', '(r-0.3)*(r-0.8-0.12*cos(10*t))*(r-1.3-0.18*cos(10*t))', 1.8),
  example('mandala-shell', 'Concha ornamental', 'Mandalas', 'Anillos que se ondulan en veinte direcciones.', 'sin(11*r-0.7*cos(10*t))', 2.3),
  example('metaballs2', 'Dos gotas', 'Orgánicas', 'Dos fuentes gaussianas se fusionan en una gota.', 'exp(-2*((x-0.7)**2+y*y))+exp(-2*((x+0.7)**2+y*y))-0.55', 2),
  example('metaballs3', 'Tres gotas', 'Orgánicas', 'Tres manchas suaves forman una silueta triangular.', 'exp(-2*((x-0.8)**2+y*y))+exp(-2*((x+0.4)**2+(y-0.7)**2))+exp(-2*((x+0.4)**2+(y+0.7)**2))-0.5', 2),
  example('metaballs4', 'Célula de cuatro núcleos', 'Orgánicas', 'Cuatro lóbulos se funden sin esquinas.', 'exp(-2*((x-0.8)**2+y*y))+exp(-2*((x+0.8)**2+y*y))+exp(-2*(x*x+(y-0.8)**2))+exp(-2*(x*x+(y+0.8)**2))-0.65', 2),
  example('amoeba', 'Ameba', 'Orgánicas', 'Una silueta irregular de lóbulos suaves.', 'r-1-0.22*sin(3*t)-0.18*cos(5*t)-0.1*sin(7*t)', 1.8),
  example('coral', 'Coral', 'Orgánicas', 'Ondas de varias escalas dibujan celdas sinuosas.', 'sin(3*x+cos(2*y))+sin(3*y+cos(2*x))+0.4*sin(7*x+5*y)', 3),
  example('fingerprint', 'Huella dactilar', 'Orgánicas', 'Arcos concéntricos deformados como una huella.', 'sin(9*sqrt(x*x+0.6*y*y)+1.2*sin(2*y))', 2.5),
  example('wood', 'Vetas de madera', 'Orgánicas', 'Anillos elípticos que se deforman suavemente.', 'sin(7*hypot(x+0.2*sin(3*y),0.6*y)+sin(2*x))', 3),
  example('topography', 'Mapa topográfico', 'Orgánicas', 'Curvas de nivel de una superficie ondulada.', 'sin(6*(sin(x)*cos(y)+0.35*sin(2*x+3*y)))', 3),
  example('islands', 'Archipiélago', 'Orgánicas', 'Contornos de islas de distintas escalas.', 'sin(2*x)*cos(2*y)+0.35*cos(5*x+2*y)+0.2*sin(3*x-5*y)-0.4', 3),
  example('electric', 'Campo eléctrico visual', 'Orgánicas', 'Contornos suaves alrededor de tres focos.', '1/sqrt((x-1)**2+y*y+0.1)-1/sqrt((x+1)**2+y*y+0.1)+0.4/sqrt(x*x+(y-1.2)**2+0.1)', 3),
  example('fermat', 'Óvalo de Fermat', 'Algebraicas', 'Cuatro lados suaves con curvatura muy marcada.', 'x**6+y**6-1', 1.4),
  example('cross', 'Cruz redondeada', 'Algebraicas', 'Una cruz simétrica con brazos amplios.', 'x**4+y**4-2.5*x*x*y*y-1', 2),
  example('algebraic-flower', 'Flor algebraica', 'Algebraicas', 'Un contorno cuártico con lóbulos diagonales.', '(x*x+y*y)**2-1.6*x*x*y*y-1', 1.7),
  example('sextic', 'Sextica estrellada', 'Algebraicas', 'Una curva de sexto grado con seis lóbulos.', '(x*x+y*y)**3-0.8*(x**3-3*x*y*y)-1', 1.6),
  example('quartic-cross', 'Cuatro islas', 'Algebraicas', 'Cuatro óvalos aislados en los cuadrantes.', '(x*x-1)**2+(y*y-1)**2-0.4', 1.7),
  example('double-ellipse', 'Elipses cruzadas', 'Algebraicas', 'Dos elipses perpendiculares se entrelazan.', '(x*x/4+y*y-1)*(x*x+y*y/4-1)', 2.5),
  example('three-circles', 'Trinidad de círculos', 'Algebraicas', 'Tres círculos superpuestos de forma triangular.', '((x-0.65)**2+y*y-1)*((x+0.65)**2+y*y-1)*(x*x+(y-0.8)**2-1)', 2.2),
  example('concentric-ellipses', 'Óvalos anidados', 'Algebraicas', 'Cuatro elipses dibujadas en una sola expresión.', '(x*x/2+y*y-0.2)*(x*x/2+y*y-0.6)*(x*x/2+y*y-1.2)*(x*x/2+y*y-2)', 2.4),
  example('gaussian-curve', 'Campana normal', 'Especiales', 'La densidad normal, ampliada para apreciar su silueta.', 'y-3*normalPDF(x)', 3),
  example('erf-curve', 'Curva de error', 'Especiales', 'Una transición sigmoide suave.', 'y-erf(2*x)', 2),
  example('lambert-curve', 'Lambert W', 'Especiales', 'La curva que invierte w·exp(w).', 'y-lambertW(x)', 2, [-0.36, 5, -1.3, 2.3]),
  example('gamma-curve', 'Arco de Gamma', 'Especiales', 'Un valle asimétrico entre crecimientos rápidos.', 'y-logGamma(x)', 2, [0.05, 5, -1, 4]),
  example('sinc-ripples', 'Ondas de sinc', 'Especiales', 'Una onda central y oscilaciones que se apagan.', 'y-sinc(4*x)', 3),
  example('chebyshev-wave', 'Onda de Chebyshev', 'Especiales', 'Oscilaciones polinómicas concentradas en los extremos.', 'y-chebyshevT(12,x)', 1.3),
  example('hermite-curve', 'Hermite suavizado', 'Especiales', 'Un polinomio recortado por una campana gaussiana.', 'y-hermiteHe(5,x)*exp(-x*x/2)/3', 3),
  example('beta-arches', 'Arco de Bernstein', 'Especiales', 'Un arco asimétrico de una base polinómica.', 'y-5*bernstein(8,3,x)', 1, [-0.1, 1.1, -0.2, 1.8]),
  ...createExtendedExamples(example),
];
