export interface IntegrationMethod {
  id: string;
  title: string;
  idea: string;
  formula: string;
  example: string;
  caution: string;
}
export interface IntegrationChapter {
  title: string;
  route: string;
  intro: string;
  prerequisites: string;
  methods: IntegrationMethod[];
}
const tex = String.raw;

export const CLASSICAL_INTEGRATION: IntegrationChapter = {
  title: 'Integrales I: técnicas clásicas', route: 'integration-classical',
  intro: 'Integrar es reconocer una estructura. A veces buscamos una función cuya derivada conocemos; otras, un área o una acumulación que puede calcularse sin encontrar ninguna primitiva. Este recorrido empieza por las reglas elementales y construye una caja de herramientas para decidir qué transformación simplifica cada problema.',
  prerequisites: 'Derivadas, funciones elementales y el significado de una integral definida.',
  methods: [
    { id: 'fundamental', title: '1. Primitivas, linealidad y teorema fundamental',
      idea: 'La primera pregunta es si el integrando es una derivada conocida. La linealidad permite separar sumas y extraer constantes. Para una función continua en un intervalo, cualquier primitiva permite evaluar su integral definida restando los valores en los extremos.',
      formula: tex`\int_a^b f(x)\,dx=F(b)-F(a),\quad F'=f;\qquad \int(3x^2+2\cos x)\,dx=x^3+2\sin x+C`,
      example: 'En [0,1], la parte polinómica aporta 1 y la trigonométrica 2 sen(1). Para comprobar una primitiva basta derivarla. La constante C aparece en la integral indefinida; desaparece al restar extremos.',
      caution: 'Una integral definida no es siempre un área positiva: las regiones bajo el eje contribuyen con signo negativo. En dominios desconectados puede haber una constante distinta en cada intervalo.' },
    { id: 'algebra', title: '2. Simplificar antes de integrar',
      idea: 'Dividir polinomios, completar cuadrados, desarrollar un producto pequeño o separar un cociente puede revelar primitivas inmediatas. Conviene transformar la expresión antes de escoger un método más costoso.',
      formula: tex`\frac{x^2}{1+x^2}=1-\frac1{1+x^2},\qquad \int\frac{x^2}{1+x^2}\,dx=x-\arctan x+C`,
      example: 'El denominador casi coincide con el numerador: escribir x²=(1+x²)−1 elimina la aparente dificultad. Completar x²+2x+2=(x+1)²+1 produce de igual modo una arctangente trasladada.',
      caution: 'Una cancelación algebraica no autoriza a ignorar un punto donde la expresión original no está definida; hay que determinar si la singularidad es removible.' },
    { id: 'substitution', title: '3. Sustitución: la regla de la cadena al revés',
      idea: 'Busca una función interior acompañada de su derivada. Al introducir u=g(x), todo el integrando debe quedar expresado en u, incluido el diferencial. En una integral definida transforma también los extremos.',
      formula: tex`\int_0^b 2x(1+x^2)\,dx=\int_0^{b^2}(1+u)\,du=b^2+\frac{b^4}{2},\qquad u=x^2,\ b\ge0`,
      example: 'El factor 2x compensa la deformación de la escala horizontal. El laboratorio muestra que las curvas tienen formas distintas, pero sus áreas sombreadas coinciden. Otra señal frecuente es f′/f, cuya primitiva es ln|f|.',
      caution: 'Para usar una inversa hay que escoger una rama válida. Si el cambio no es inyectivo, puede ser necesario dividir el intervalo; nunca reemplaces dx por du sin su factor.' },
    { id: 'parts', title: '4. Integración por partes',
      idea: 'La regla del producto permite trasladar una derivada de un factor al otro. Es útil cuando derivar un polinomio o un logaritmo simplifica el problema y el segundo factor se integra fácilmente.',
      formula: tex`\int u\,dv=uv-\int v\,du;\qquad \int x e^x\,dx=xe^x-\int e^x\,dx=e^x(x-1)+C`,
      example: 'Para integrar ln x, toma u=ln x y dv=dx: el resultado es x ln x−x+C en x>0. Elegir u no es una regla mecánica; prueba si la nueva integral es realmente más sencilla.',
      caution: 'En integrales definidas conserva el término de borde [uv]. En intervalos impropios hay que justificar el límite de ese término y la convergencia de las integrales restantes.' },
    { id: 'tabular', title: '5. Partes repetidas, tabla y ciclos',
      idea: 'La versión tabular organiza derivadas sucesivas de un polinomio y primitivas de una exponencial o seno. Si vuelve a aparecer la integral inicial, trátala como una incógnita y despeja.',
      formula: tex`\int x^2e^x\,dx=e^x(x^2-2x+2)+C,\qquad \int e^x\cos x\,dx=\frac{e^x}{2}(\sin x+\cos x)+C`,
      example: 'En el primer caso, las derivadas x², 2x, 2, 0 hacen terminar la tabla. En el segundo, dos integraciones por partes dan I=eˣ cos x+eˣ sen x−I; mover −I al otro miembro cierra el ciclo.',
      caution: 'Alterna los signos de la tabla. Un ciclo solo sirve si la ecuación obtenida aporta información, y no si acaba en la identidad I=I.' },
    { id: 'rational', title: '6. Fracciones parciales',
      idea: 'Toda función racional puede abordarse con división polinómica y descomposición del resto. Los factores lineales generan logaritmos; los cuadráticos irreducibles, logaritmos y arctangentes tras completar cuadrados.',
      formula: tex`\frac1{x^2-1}=\frac12\left(\frac1{x-1}-\frac1{x+1}\right),\qquad \int\frac{dx}{x^2-1}=\frac12\ln\left|\frac{x-1}{x+1}\right|+C`,
      example: 'Para un factor repetido (x−a)ᵐ incluye todas las potencias desde 1 hasta m. Sobre un cuadrático irreducible, el numerador de cada término debe ser lineal, no solo constante.',
      caution: 'La primitiva es válida por intervalos separados por los polos. No evalúes a través de x=±1 con una simple resta de valores.' },
    { id: 'trig-identities', title: '7. Identidades y potencias trigonométricas',
      idea: 'Las identidades de ángulo doble y producto a suma convierten productos en sumas. Si hay una potencia impar de seno o coseno, reserva un factor para el diferencial y expresa el resto mediante la identidad pitagórica.',
      formula: tex`\int\sin^2x\,dx=\frac x2-\frac{\sin 2x}{4}+C,\qquad \int\sin^3x\,dx=-\cos x+\frac{\cos^3x}{3}+C`,
      example: 'Para sen³x escribe (1−cos²x)sen x y toma u=cos x. Para sen²x usa (1−cos 2x)/2. Las potencias de tangente y secante se tratan reservando sec²x o sec x tan x cuando corresponda.',
      caution: 'Las identidades pueden simplificar una potencia y complicar otra. Inspecciona la paridad antes de expandir todo.' },
    { id: 'trig-substitution', title: '8. Sustituciones trigonométricas',
      idea: 'Las raíces de a²−x², a²+x² y x²−a² sugieren x=a sen θ, x=a tan θ y x=a sec θ, respectivamente. La raíz desaparece gracias a una identidad pitagórica.',
      formula: tex`\int\sqrt{a^2-x^2}\,dx=\frac x2\sqrt{a^2-x^2}+\frac{a^2}{2}\arcsin(x/a)+C,\quad a>0`,
      example: 'Con x=a sen θ y θ entre −π/2 y π/2, la raíz es a cos θ y dx=a cos θ dθ. Queda a²∫cos²θ dθ; la identidad de ángulo doble resuelve la integral.',
      caution: 'La raíz de cos²θ es |cos θ|. La elección del intervalo de θ es lo que permite eliminar el valor absoluto.' },
    { id: 'hyperbolic', title: '9. Sustituciones hiperbólicas',
      idea: 'La identidad cosh²t−senh²t=1 suele tratar raíces con menos restricciones de ángulo. Para √(x²+a²), el cambio x=a senh t deja una expresión con cosh t.',
      formula: tex`\int\frac{dx}{\sqrt{x^2+a^2}}=\operatorname{arsinh}(x/a)+C=\ln\left(x+\sqrt{x^2+a^2}\right)+C',\quad a>0`,
      example: 'El diferencial a cosh t dt cancela exactamente el denominador a cosh t. Esta ruta es especialmente cómoda para x real sin separar signos.',
      caution: 'Para √(x²−a²), x=a cosh t solo cubre la rama x≥a; la rama x≤−a requiere otro cambio.' },
    { id: 'weierstrass', title: '10. Sustitución universal de Weierstrass',
      idea: 'Una expresión racional en sen x y cos x se vuelve racional en t=tan(x/2). Esto ofrece un procedimiento sistemático cuando las identidades trigonométricas no muestran un atajo.',
      formula: tex`\sin x=\frac{2t}{1+t^2},\quad \cos x=\frac{1-t^2}{1+t^2},\quad dx=\frac{2\,dt}{1+t^2};\qquad \int\frac{dx}{2+\cos x}=\frac2{\sqrt3}\arctan\frac{t}{\sqrt3}+C`,
      example: 'Al sustituir en el ejemplo se obtiene 2∫dt/(t²+3), una arctangente. El cambio racionaliza todo el cociente, aunque a veces produce polinomios grandes.',
      caution: 't tiene saltos en los múltiplos impares de π. La fórmula de la primitiva se interpreta localmente; una integral que cruza esos puntos debe partirse.' },
    { id: 'euler', title: '11. Sustituciones de Euler y potencias racionales',
      idea: 'Las sustituciones de Euler racionalizan √(ax²+bx+c). Cuando a>0, una opción es igualar la raíz a √a·x+t y despejar x como función racional de t. Para potencias fraccionarias de x, usa una potencia cuyo exponente elimine los denominadores.',
      formula: tex`\sqrt{ax^2+bx+c}=\sqrt a\,x+t\ \Longrightarrow\ x=\frac{t^2-c}{b-2\sqrt a\,t};\qquad \int\frac{dx}{1+\sqrt x}=2\sqrt x-2\ln(1+\sqrt x)+C`,
      example: 'En el segundo ejemplo, x=t² y dx=2t dt convierten la integral en ∫2t/(1+t)dt. Otras variantes de Euler aprovechan c>0 o una raíz real del cuadrático.',
      caution: 'Al elevar al cuadrado se pueden introducir ramas ajenas a la raíz original. Comprueba signos, denominadores y el dominio de la sustitución.' },
    { id: 'reduction', title: '12. Fórmulas de reducción y recurrencias',
      idea: 'En una familia indexada por un entero no hace falta resolver cada integral desde cero: por partes puede relacionar el caso n con uno más pequeño.',
      formula: tex`I_n=\int_0^{\pi/2}\sin^n x\,dx=\frac{n-1}{n}I_{n-2},\quad n\ge2;\qquad I_0=\frac\pi2,\ I_1=1,\ I_4=\frac{3\pi}{16}`,
      example: 'Separa senⁿ⁻¹x·sen x, integra el último factor y deriva el primero. Sustituir cos²x=1−sen²x permite despejar Iₙ. Dos valores iniciales resuelven todos los exponentes enteros no negativos.',
      caution: 'El intervalo fija los términos de borde y las condiciones iniciales. Una recurrencia para integrales definidas no se traslada sin más a primitivas.' },
    { id: 'symmetry', title: '13. Simetría, reflexión y periodicidad',
      idea: 'Antes de calcular, compara f(x) con f(−x), f(a+b−x) o una traslación por un período. Sumar una integral a su reflejo puede hacer desaparecer la parte complicada.',
      formula: tex`\int_0^a f(x)\,dx=\int_0^a f(a-x)\,dx;\qquad \int_0^{\pi/2}\frac{\sin x}{\sin x+\cos x}\,dx=\frac\pi4`,
      example: 'Al reflejar x en π/2−x se intercambian seno y coseno. Las dos integrandas suman 1, así que dos veces la integral vale π/2. Para funciones impares integrables sobre [−a,a], el resultado es cero.',
      caution: 'La simetría no convierte una integral divergente en convergente. El valor principal simétrico y la integral impropia ordinaria son conceptos distintos.' },
    { id: 'improper', title: '14. Integrales impropias: calcular después de comprobar',
      idea: 'Una singularidad o un extremo infinito se trata con límites. La comparación y los equivalentes locales deciden primero si existe un valor finito. Si hay una singularidad interior, los límites laterales deben converger por separado.',
      formula: tex`\int_1^\infty x^{-p}\,dx=\frac1{p-1}\ (p>1),\qquad \int_0^1 x^{-p}\,dx=\frac1{1-p}\ (p<1)`,
      example: 'La misma potencia exige condiciones opuestas en cero y en infinito. La integral de 1/x en [−1,1] diverge como integral impropia, aunque su valor principal de Cauchy sea cero.',
      caution: 'No se pueden cancelar infinitos de extremos distintos. Una primitiva formal solo resuelve el problema cuando los límites requeridos existen.' },
  ],
};

export const ADVANCED_INTEGRATION: IntegrationChapter = {
  title: 'Integrales II: parámetros, contornos y asintótica', route: 'integration-advanced',
  intro: 'Hay integrales que se resisten a todas las sustituciones elementales. La salida puede ser añadir un parámetro, otra dimensión o una variable compleja. También puede consistir en aceptar una función especial o buscar una aproximación cuyo error disminuye en un límite bien definido.',
  prerequisites: 'Técnicas clásicas; para las últimas secciones, series, números complejos y nociones de convergencia.',
  methods: [
    { id: 'feynman', title: '1. Derivación bajo el signo integral',
      idea: 'Introduce un parámetro para obtener una integral cuya derivada sea más sencilla. Después integra respecto al parámetro y recupera la constante con un valor conocido. Es una técnica asociada popularmente a Feynman.',
      formula: tex`F(a)=\int_0^1\frac{\ln(1+ax)}x\,dx,\quad F'(a)=\int_0^1\frac{dx}{1+ax}=\frac{\ln(1+a)}a,\quad F(0)=0`,
      example: 'En a=0, el cociente de la última expresión tiene límite 1. Para a≥0 en cualquier intervalo compacto de parámetros, la derivada del integrando está acotada por 1: esto justifica pasar la derivada al interior. En el laboratorio puedes seguir las dos funciones.',
      caution: 'La continuidad aislada en cada parámetro no basta en general. Una condición suficiente es una cota integrable uniforme para la derivada en un entorno del parámetro.' },
    { id: 'frullani', title: '2. Frullani: diferencias que cancelan divergencias',
      idea: 'La diferencia entre una función evaluada a dos escalas puede ser integrable aunque sus términos separados no lo sean. Un parámetro permite descubrir que el resultado depende de un logaritmo de escalas.',
      formula: tex`\int_0^\infty\frac{e^{-ax}-e^{-bx}}x\,dx=\ln\frac ba,\qquad a,b>0`,
      example: 'Derivar respecto a b deja ∫₀∞e⁻ᵇˣdx=1/b. La integral es cero cuando b=a, y eso fija ln(b/a). Cerca del origen el numerador es (b−a)x+O(x²), de modo que el cociente tiene límite finito.',
      caution: 'No separes esta integral en dos integrales de e⁻ᵃˣ/x: ambas divergen en cero. Las versiones generales de Frullani necesitan hipótesis sobre f y su comportamiento en los extremos.' },
    { id: 'series', title: '3. Integración término a término',
      idea: 'Una serie convierte un integrando difícil en una sucesión de integrales sencillas. La convergencia uniforme, la convergencia dominada o la monotonía positiva pueden justificar el intercambio.',
      formula: tex`\int_0^r\frac{\ln(1+x)}x\,dx=\sum_{n=1}^\infty\frac{(-1)^{n+1}r^n}{n^2},\qquad 0\le r\le1`,
      example: 'Para r<1 se integra la serie de ln(1+x)/x uniformemente. El extremo r=1 se obtiene por un argumento de límite dominado; allí la suma vale π²/12. No hace falta una primitiva elemental.',
      caution: 'En el borde del radio de convergencia hay que revisar el argumento. Una serie asintótica no es necesariamente una serie convergente que se pueda sumar hasta infinito.' },
    { id: 'fubini', title: '4. Fubini, Tonelli y cambiar el orden',
      idea: 'Representar el integrando mediante otra integral permite intercambiar el orden y escoger el que resulte más fácil. Tonelli admite integrandos no negativos; Fubini permite el intercambio cuando hay integrabilidad absoluta.',
      formula: tex`\int_0^1\int_x^1 e^{y^2}\,dy\,dx=\int_0^1\int_0^y e^{y^2}\,dx\,dy=\int_0^1 y e^{y^2}\,dy=\frac{e-1}{2}`,
      example: 'La región es el triángulo 0≤x≤y≤1. En el orden original aparece una primitiva no elemental; al integrar primero respecto a x surge el factor y que permite sustituir u=y².',
      caution: 'Dibuja o describe la región antes de cambiar los límites. Tonelli puede dar infinito; no garantiza por sí solo un resultado finito.' },
    { id: 'gaussian', title: '5. Elevar al cuadrado y pasar a coordenadas polares',
      idea: 'Una integral positiva sobre la recta puede multiplicarse por sí misma y convertirse en una integral doble. La simetría radial hace que el cambio a polares elimine la dificultad.',
      formula: tex`I=\int_{-\infty}^{\infty}e^{-x^2}\,dx,\quad I^2=\int_0^{2\pi}\int_0^\infty e^{-r^2}r\,dr\,d\theta=\pi,\quad I=\sqrt\pi`,
      example: 'El jacobiano r es esencial: precisamente convierte la integral radial en una sustitución inmediata. La raíz positiva se elige porque el integrando original es positivo.',
      caution: 'La transformación multidimensional incluye siempre el valor absoluto del determinante jacobiano. Omitirlo altera la medida, no solo la notación.' },
    { id: 'beta-gamma', title: '6. Reconocer funciones beta y gamma',
      idea: 'Las funciones especiales reúnen familias enteras de integrales. Reducir una integral a beta o gamma proporciona identidades, recurrencias y métodos de evaluación sin exigir una expresión elemental.',
      formula: tex`B(p,q)=\int_0^1t^{p-1}(1-t)^{q-1}dt=\frac{\Gamma(p)\Gamma(q)}{\Gamma(p+q)},\quad p,q>0;\qquad \int_0^\infty x^m e^{-a x^r}dx=\frac{\Gamma((m+1)/r)}{r a^{(m+1)/r}}`,
      example: 'En la segunda identidad, a,r>0 y m>−1. El cambio t=axʳ produce exactamente la integral que define gamma. Para m=0, r=2 se recupera la mitad de la gaussiana con escala a.',
      caution: 'La prolongación analítica de beta o gamma puede existir donde la integral original diverge. Las condiciones de la representación integral siguen siendo necesarias.' },
    { id: 'mellin', title: '7. Transformadas de Laplace, Fourier y Mellin',
      idea: 'Una transformada es una integral con un núcleo organizado: exponencial amortiguada, oscilación o potencia. Sus tablas y reglas de escala convierten nuevas integrales en evaluaciones de una función ya conocida.',
      formula: tex`\mathcal M[f](s)=\int_0^\infty x^{s-1}f(x)dx;\qquad \int_0^\infty\frac{x^{s-1}}{1+x}dx=\Gamma(s)\Gamma(1-s)=\frac\pi{\sin\pi s},\quad 0<s<1`,
      example: 'Con t=x/(1+x), la integral se convierte en B(s,1−s). Mellin es natural para problemas de escala; Laplace para decaimiento y ecuaciones diferenciales; Fourier para oscilaciones y convoluciones.',
      caution: 'La franja de convergencia forma parte de la fórmula. Para parámetros complejos, en este ejemplo se requiere 0<Re(s)<1.' },
    { id: 'residues', title: '8. Teorema de los residuos',
      idea: 'Extiende una función racional al plano complejo y cierra el camino real con un arco. Si la contribución del arco desaparece, la integral real se obtiene de los polos encerrados.',
      formula: tex`\oint_C f(z)dz=2\pi i\sum\operatorname{Res}(f;z_k),\qquad \int_{-\infty}^{\infty}\frac{dx}{1+x^2}=2\pi i\frac1{2i}=\pi`,
      example: 'En el semiplano superior solo está el polo i. Su residuo es 1/(2i). Sobre un semicírculo de radio R>1, el módulo de la integral del arco es como máximo πR/(R²−1), que tiende a cero.',
      caution: 'El contorno debe evitar los polos. La integral cerrada es π para R>1, pero la integral sobre el segmento [−R,R] es 2 arctan R: el arco aún contribuye para R finito.' },
    { id: 'keyhole', title: '9. Contornos de cerradura y cortes de rama',
      idea: 'Para potencias no enteras y logaritmos hay que elegir una rama. Un contorno rodea el corte y relaciona los valores en sus dos orillas; el salto de fase permite despejar la integral real.',
      formula: tex`\int_0^\infty\frac{x^{a-1}}{1+x}\,dx=\frac\pi{\sin(\pi a)},\qquad 0<a<1`,
      example: 'Para zᵃ⁻¹ con argumento entre 0 y 2π, las dos orillas del eje positivo difieren por e²πⁱᵃ. El polo en −1 aporta el residuo eⁱπ⁽ᵃ⁻¹⁾. La identidad resultante es (1−e²πⁱᵃ)I=2πi eⁱπ⁽ᵃ⁻¹⁾.',
      caution: 'Los círculos pequeño y grande desaparecen precisamente por a>0 y a<1. Hay que conservar la orientación opuesta de las dos orillas.' },
    { id: 'green', title: '10. Green, Stokes y el teorema de la divergencia',
      idea: 'En varias dimensiones, algunos integrandos son derivadas de campos. Los teoremas integrales convierten una integral sobre una región en otra sobre su borde, o al revés.',
      formula: tex`\operatorname{Área}(D)=\frac12\oint_{\partial D}(x\,dy-y\,dx);\qquad x=a\cos t,\ y=b\sin t\ \Longrightarrow\ \operatorname{Área}=\pi ab`,
      example: 'Para la elipse orientada en sentido antihorario, x dy−y dx=ab dt. Integrar de 0 a 2π y dividir entre dos da su área. Stokes relaciona circulación y rotacional; Gauss relaciona flujo y divergencia.',
      caution: 'Se necesitan la regularidad apropiada del campo y del dominio, y una orientación compatible. Un campo singular dentro de la región puede invalidar la aplicación directa.' },
    { id: 'laplace', title: '11. Método de Laplace',
      idea: 'Cuando un parámetro grande multiplica una función en una exponencial negativa, domina la zona próxima al mínimo. Aproximar allí por una parábola reduce el problema a una gaussiana.',
      formula: tex`\int_a^b g(x)e^{-\lambda\phi(x)}dx\sim g(x_0)e^{-\lambda\phi(x_0)}\sqrt{\frac{2\pi}{\lambda\phi''(x_0)}},\qquad \lambda\to+\infty`,
      example: 'La fórmula supone un mínimo interior único no degenerado, φ″(x₀)>0, y amplitud suave con g(x₀)≠0. En el laboratorio φ(t)=t²/2+t⁴/4 tiene su mínimo en cero: el término principal es √(2π/λ).',
      caution: 'El símbolo ∼ expresa un cociente que tiende a 1. No es una igualdad para λ finito; mínimos en extremos o degenerados requieren otras escalas.' },
    { id: 'watson', title: '12. Lema de Watson',
      idea: 'Si la masa se concentra junto a un extremo, expande localmente la amplitud en potencias. Cada potencia integrada contra una exponencial aporta un término gamma al desarrollo asintótico.',
      formula: tex`\int_0^\infty\frac{e^{-\lambda t}}{1+t}dt\sim\frac1\lambda-\frac1{\lambda^2}+\frac{2!}{\lambda^3}-\frac{3!}{\lambda^4}+\cdots`,
      example: 'La expansión local 1/(1+t)=1−t+t²−… produce los factoriales al integrar cada monomio. Para una aproximación útil se conserva un número finito de términos mientras λ crece.',
      caution: 'La serie factorial diverge para todo λ finito. Su utilidad es asintótica; añadir términos indefinidamente puede empeorar la aproximación.' },
    { id: 'stationary', title: '13. Fase estacionaria',
      idea: 'En una integral muy oscilatoria casi todo se cancela. Cerca de un punto donde la derivada de la fase se anula, la oscilación se ralentiza y aparece una contribución dominante.',
      formula: tex`\int_a^b g(x)e^{i\omega\phi(x)}dx\sim g(x_0)e^{i\omega\phi(x_0)+i\pi\,\operatorname{sgn}(\phi''(x_0))/4}\sqrt{\frac{2\pi}{\omega|\phi''(x_0)|}}`,
      example: 'La expresión describe un punto estacionario interior aislado y no degenerado, con ω→+∞ y amplitud suave. Para la fase x²/2, la contribución local contiene el factor eⁱπ/⁴√(2π/ω).',
      caution: 'Si hay varios puntos estacionarios, se suman sus contribuciones complejas y pueden interferir. Los extremos y los puntos degenerados se analizan por separado.' },
    { id: 'steepest', title: '14. Descenso más pronunciado y puntos de silla',
      idea: 'Deforma un camino complejo hasta que la fase sea constante y la parte real del exponente disminuya al alejarse de un punto crítico. Así una integral oscilatoria se convierte localmente en otra de decaimiento.',
      formula: tex`I(\lambda)=\int_C e^{\lambda f(z)}g(z)dz,\qquad f'(z_0)=0,\qquad f(z)\approx f(z_0)+\tfrac12 f''(z_0)(z-z_0)^2`,
      example: 'Para exp(iωz²/2), rotar localmente el camino a z=eⁱπ/⁴t convierte el exponente en −ωt²/2. La rotación del diferencial explica el factor de fase de la fórmula anterior.',
      caution: 'La deformación global debe justificarse: no puede cruzar singularidades sin contabilizarlas. Cuando dos puntos de silla se fusionan se requieren aproximaciones uniformes, frecuentemente con funciones de Airy.' },
    { id: 'risch', title: '15. Liouville, Risch y funciones no elementales',
      idea: 'La integración simbólica también consiste en decidir cuándo una primitiva elemental no existe. La teoría de Liouville y los algoritmos de tipo Risch convierten esa pregunta en un problema algebraico dentro de clases precisas de funciones.',
      formula: tex`\int e^{-x^2}dx=\frac{\sqrt\pi}{2}\operatorname{erf}(x)+C,\qquad \int\frac{dx}{\sqrt{(1-x^2)(1-k^2x^2)}}=F(\arcsin x,k)+C`,
      example: 'La primera integral define la función error; la segunda, en una rama real apropiada, una integral elíptica incompleta de primera especie. Poner nombre a estas funciones permite estudiarlas, aproximarlas y relacionarlas.',
      caution: 'Que una primitiva no sea elemental no significa que una integral definida carezca de valor exacto. Un sistema de álgebra también puede fallar por limitaciones de implementación.' },
    { id: 'creative', title: '16. Telescopaje creativo y ecuaciones para integrales',
      idea: 'En lugar de integrar directamente, busca una relación diferencial o una recurrencia satisfecha por toda la familia. Si una combinación de derivadas respecto al parámetro es una derivada respecto a x, la integración deja solo términos de borde.',
      formula: tex`I_n=\int_0^1 x^n(1-x)^n dx=\frac{(n!)^2}{(2n+1)!},\qquad I_{n+1}=\frac{n+1}{2(2n+3)}I_n,\quad I_0=1`,
      example: 'Esta familia ilustra cómo una recurrencia y un dato inicial determinan todas las integrales. El telescopaje creativo automatiza la búsqueda de relaciones semejantes para numerosas familias hipergeométricas y holonómicas.',
      caution: 'La relación debe ir acompañada de sus términos de borde y datos iniciales. Una ecuación diferencial por sí sola suele admitir muchas soluciones.' },
    { id: 'mellin-barnes', title: '17. Mellin–Barnes: de una integral a una suma de residuos',
      idea: 'Una integral sobre una línea vertical compleja puede representar una función y separar sus escalas. Al desplazar la línea se recogen residuos que generan series o expansiones asintóticas.',
      formula: tex`(1+x)^{-a}=\frac1{2\pi i\,\Gamma(a)}\int_{c-i\infty}^{c+i\infty}\Gamma(s)\Gamma(a-s)x^{-s}ds,\quad x>0,\quad 0<c<a`,
      example: 'Para a>0, los polos de Γ(s) quedan a un lado y los de Γ(a−s) al otro. Desplazar hacia los polos s=0,−1,−2,… produce la expansión binomial en potencias de x para 0<x<1.',
      caution: 'Hay que justificar el decaimiento en los segmentos auxiliares. Una representación de contorno no convierte cualquier desplazamiento en una suma convergente.' },
  ],
};

export const NUMERICAL_INTEGRATION: IntegrationChapter = {
  title: 'Integrales III: cuadratura y métodos computacionales', route: 'integration-numerical',
  intro: 'Cuando lo que necesitamos es un número, una primitiva puede ser un rodeo innecesario. La integración numérica distribuye evaluaciones del integrando para obtener precisión con un coste controlado. El reto no es mostrar muchos decimales: es saber cuáles son fiables.',
  prerequisites: 'Integrales definidas, nociones de error y, para Monte Carlo, probabilidad elemental.',
  methods: [
    { id: 'riemann', title: '1. Rectángulos y punto medio',
      idea: 'Divide [a,b] en n paneles y reemplaza el integrando por una constante en cada uno. Evaluar en el centro suele cancelar el error de primer orden que presentan los rectángulos de extremo.',
      formula: tex`M_n=h\sum_{j=0}^{n-1}f\left(a+(j+\tfrac12)h\right),\quad h=\frac{b-a}{n};\qquad |I-M_n|\le\frac{(b-a)h^2}{24}\max|f''|`,
      example: 'Para f(x)=x² en [0,1], un solo punto medio da 1/4 frente a 1/3. Al duplicar n, el error baja aproximadamente por un factor cuatro cuando f es suficientemente suave.',
      caution: 'La cota requiere una segunda derivada acotada. Un pico estrecho entre nodos puede quedar casi invisible para una malla gruesa.' },
    { id: 'newton-cotes', title: '2. Trapecio, Simpson y Newton–Cotes',
      idea: 'Integra un polinomio interpolador en cada panel o pareja de paneles. El trapecio une extremos con rectas; Simpson utiliza parábolas y es exacto para polinomios de grado hasta tres.',
      formula: tex`T_n=h\left[\frac{f(a)+f(b)}2+\sum_{j=1}^{n-1}f(a+jh)\right],\qquad S_n=\frac{4T_n-T_{n/2}}3\quad(n\text{ par})`,
      example: 'Para x³ en [0,1], Simpson con dos paneles da exactamente 1/4. En el laboratorio se dibujan los interpoladores: cambia a √x para observar cómo la pérdida de suavidad afecta a la convergencia.',
      caution: 'El error compuesto de Simpson es O(h⁴) si la cuarta derivada está acotada. Las fórmulas de Newton–Cotes de grado muy alto pueden tener pesos negativos y amplificar errores.' },
    { id: 'romberg', title: '3. Richardson y Romberg',
      idea: 'Si se conoce la forma dominante del error, combina dos aproximaciones para cancelarla. Romberg repite esta extrapolación sobre una secuencia de trapecios con pasos cada vez menores.',
      formula: tex`R_{k,0}=T_{2^k},\qquad R_{k,j}=R_{k,j-1}+\frac{R_{k,j-1}-R_{k-1,j-1}}{4^j-1}`, 
      example: 'La primera columna extrapolada es Simpson. Cada nueva columna elimina otra potencia par de h cuando la expansión del error lo permite, reutilizando evaluaciones previas.',
      caution: 'Las singularidades y la falta de suavidad pueden romper esa expansión. Extrapolar no corrige automáticamente datos ruidosos ni errores de redondeo.' },
    { id: 'gauss', title: '4. Cuadraturas gaussianas',
      idea: 'Permitir que los nodos se muevan, en lugar de fijarlos equidistantes, maximiza el grado de exactitud. Una regla de Gauss con m nodos integra exactamente polinomios de grado hasta 2m−1 con el peso correspondiente.',
      formula: tex`\int_{-1}^1f(x)dx\approx f(-1/\sqrt3)+f(1/\sqrt3)`,
      example: 'Es Gauss–Legendre de dos nodos. Un cambio afín la lleva a cada panel del laboratorio. Gauss–Laguerre incorpora el peso e⁻ˣ en [0,∞), Gauss–Hermite el peso e⁻ˣ² y Gauss–Jacobi pesos algebraicos en [−1,1].',
      caution: 'La exactitud polinómica no es una cota universal del error. Elegir una familia con un peso distinto al de la integral exige transformar el integrando correctamente.' },
    { id: 'adaptive', title: '5. Adaptación y pares Gauss–Kronrod',
      idea: 'En lugar de refinar todo el intervalo, subdivide donde dos reglas compatibles discrepan más. Gauss–Kronrod añade nodos a una regla de Gauss y reutiliza sus evaluaciones para estimar el error local.',
      formula: tex`\varepsilon_{\mathrm{local}}\approx|K-G|,\qquad \varepsilon_{\mathrm{objetivo}}=\max(\varepsilon_{\mathrm{abs}},\varepsilon_{\mathrm{rel}}|I|)`,
      example: 'Una estrategia mantiene una cola de intervalos, divide el de mayor error estimado y actualiza el total. Un pico conocido debe introducirse como punto de partición para facilitar su detección.',
      caution: 'La diferencia entre reglas es una estimación, no una prueba de exactitud. Hay que limitar evaluaciones, detectar estancamiento y declarar cuándo no se alcanza la tolerancia.' },
    { id: 'clenshaw', title: '6. Clenshaw–Curtis y aproximación espectral',
      idea: 'Interpola en nodos relacionados con cosenos, más densos junto a los extremos, y luego integra el interpolador. Los coeficientes de Chebyshev pueden calcularse mediante una transformada discreta del coseno.',
      formula: tex`x_j=\cos(j\pi/n),\qquad f(x)\approx\sum_{k=0}^n c_kT_k(x),\qquad \int_{-1}^1T_k(x)dx=\begin{cases}0&k\text{ impar},\\2/(1-k^2)&k\text{ par}.\end{cases}`,
      example: 'Los nodos se anidan al duplicar n, por lo que se reutilizan muestras. Para funciones analíticas, el decaimiento rápido de los coeficientes hace muy eficiente esta representación.',
      caution: 'Discontinuidades o singularidades reducen la velocidad de convergencia. Conviene separar el intervalo en los puntos problemáticos antes de aumentar el grado.' },
    { id: 'tanh-sinh', title: '7. Doble exponencial: tanh–sinh',
      idea: 'Un cambio de variable concentra nodos cerca de los extremos y transforma muchas singularidades integrables en colas de decaimiento muy rápido. Después se aplica el trapecio en la nueva variable.',
      formula: tex`x=\tanh\left(\frac\pi2\sinh t\right),\qquad \int_{-1}^1f(x)dx\approx h\sum_{k=-N}^N f(x(kh))x'(kh)`,
      example: 'Para f(x)=1/√(1−x²), los extremos son singulares pero la integral vale π. La transformación acerca muchísimos nodos a ±1 sin exigir una malla uniforme diminuta en toda la región.',
      caution: 'En precisión finita, x puede redondearse exactamente a ±1 y causar infinito por cero. Una implementación robusta trata esos extremos y controla tanto el paso como el truncamiento.' },
    { id: 'singular', title: '8. Sustraer singularidades y transformar el intervalo',
      idea: 'Si conocemos la parte singular, intégrala analíticamente y aplica cuadratura al resto suave. Un cambio como x=t² también puede eliminar una raíz singular del extremo.',
      formula: tex`\int_0^1\frac{g(x)}{\sqrt x}dx=2g(0)+\int_0^1\frac{g(x)-g(0)}{\sqrt x}dx=2\int_0^1g(t^2)dt`,
      example: 'La segunda igualdad es una sustitución directa; la primera separa una contribución conocida. Para un intervalo infinito, x=t/(1−t) lleva [0,∞) a [0,1), con jacobiano 1/(1−t)².',
      caution: 'Compactar un intervalo infinito puede crear una singularidad en el nuevo extremo. La cancelación g(x)−g(0) también exige cuidado numérico cuando x es muy pequeño.' },
    { id: 'oscillatory', title: '9. Filon y Levin para oscilaciones rápidas',
      idea: 'Muestrear cada oscilación es costoso. Filon aproxima la amplitud e integra exactamente sus momentos oscilatorios. Levin busca una función auxiliar cuya derivada reproduzca el integrando.',
      formula: tex`p'(x)+i\omega\phi'(x)p(x)=g(x)\ \Longrightarrow\ \int_a^b g(x)e^{i\omega\phi(x)}dx=\left[p(x)e^{i\omega\phi(x)}\right]_a^b`,
      example: 'Para fase lineal φ(x)=x, los momentos de un polinomio multiplicado por eⁱωˣ se calculan por partes. El coste puede depender de la complejidad de la amplitud, en vez del número de oscilaciones.',
      caution: 'Los puntos donde φ′=0 requieren tratamiento especial. Una malla ordinaria puede sufrir aliasing y producir una estimación de error engañosamente pequeña.' },
    { id: 'monte-carlo', title: '10. Monte Carlo',
      idea: 'Escribe la integral como una esperanza y promedia muestras. En un dominio de volumen V, muestras uniformes independientes dan un estimador insesgado V·media(f). Es útil cuando la dimensión vuelve prohibitiva una malla.',
      formula: tex`\widehat I_N=\frac VN\sum_{j=1}^Nf(X_j),\qquad \operatorname{SE}(\widehat I_N)\approx\frac{V s_f}{\sqrt N}`,
      example: 'En el cuadrado unidad, el área del cuarto de disco es π/4. Contar qué proporción de puntos cae dentro y multiplicar por cuatro estima π. El laboratorio usa una secuencia pseudoaleatoria reproducible para poder comparar tamaños de muestra.',
      caution: 'El ritmo N⁻¹/² supone varianza finita e independencia. Un intervalo estadístico no es una cota determinista, y multiplicar por diez la precisión suele exigir cien veces más muestras.' },
    { id: 'variance', title: '11. Importancia, estratificación y variables de control',
      idea: 'La precisión de Monte Carlo mejora si se reduce la varianza. Muestrea más donde la contribución es grande, reparte muestras entre estratos o resta una función correlacionada cuya integral sea conocida.',
      formula: tex`I=\mathbb E_q\!\left[\frac{f(X)}{q(X)}\right],\qquad \widehat I_{\mathrm{control}}=\overline{f-c(h-\mathbb E[h])}`,
      example: 'Para ∫₀¹x²dx, h(x)=x tiene esperanza 1/2 y está muy correlacionada con x². Restar c(x−1/2) no cambia la esperanza. Las muestras antitéticas emparejan U y 1−U para cancelar parte de la variación.',
      caution: 'La densidad q debe ser positiva donde f contribuya y producir pesos con varianza controlada. Elegir una mala densidad puede aumentar enormemente el error.' },
    { id: 'quasi-monte-carlo', title: '12. Cuasi-Monte Carlo y secuencias de baja discrepancia',
      idea: 'Halton y Sobol distribuyen puntos para cubrir el dominio de forma más uniforme que una muestra aleatoria. Se busca reducir huecos y agrupamientos, especialmente si la dimensión efectiva es moderada.',
      formula: tex`\left|\frac1N\sum_{j=1}^N f(x_j)-\int_{[0,1]^d}f(x)dx\right|\le V_{\mathrm{HK}}(f)D_N^*`,
      example: 'La desigualdad de Koksma–Hlawka relaciona el error con la variación de Hardy–Krause y la discrepancia estrella, cuando esa variación es finita. El laboratorio usa Halton en bases 2 y 3 para compararlo visualmente con el azar.',
      caution: 'La indicadora del disco no satisface automáticamente las hipótesis útiles de esa cota. No se garantiza mejorar cada muestra; para incertidumbre estadística se usan aleatorizaciones independientes, como scrambling.' },
    { id: 'sparse-grid', title: '13. Mallas dispersas y productos tensoriales',
      idea: 'En d dimensiones, una regla con m nodos por eje requiere mᵈ evaluaciones. Las mallas dispersas de Smolyak combinan reglas de varias resoluciones para reducir ese crecimiento cuando la función tiene suficiente regularidad mixta.',
      formula: tex`Q_{\mathrm{tensor}}f=\sum_{j_1=1}^m\cdots\sum_{j_d=1}^m w_{j_1}\cdots w_{j_d}f(x_{j_1},\ldots,x_{j_d})`,
      example: 'Con diez nodos por eje, pasar de dos a seis dimensiones aumenta el coste de cien a un millón. Si las interacciones de orden alto son débiles, una combinación dispersa puede ahorrar muchas evaluaciones.',
      caution: 'La dimensión por sí sola no decide el mejor método: importan la suavidad, la estructura y la dimensión efectiva. Las discontinuidades oblicuas pueden perjudicar las mallas dispersas.' },
    { id: 'validated', title: '14. Cuadratura validada y aritmética de intervalos',
      idea: 'Cuando hace falta una garantía matemática, sustituye números por intervalos con redondeo dirigido y acota también el resto de la cuadratura. El resultado es un intervalo que contiene la integral bajo hipótesis verificadas.',
      formula: tex`I\in[Q-E,Q+E],\qquad E\ge\frac{(b-a)h^4}{180}\max_{[a,b]}|f^{(4)}|\quad\text{para Simpson compuesto}`, 
      example: 'Para eˣ en [0,1], max|f⁽⁴⁾|=e. Con n par, E=e/(180n⁴) acota el error de discretización; el cálculo de Q debe incluir además el error de redondeo para que el intervalo sea certificado.',
      caution: 'La diferencia entre dos aproximaciones no es una cota validada. Los intervalos pueden ensancharse por dependencias repetidas, y la validación exige controlar todas las fuentes de error.' },
  ],
};

export const INTEGRATION_CHAPTERS = [CLASSICAL_INTEGRATION, ADVANCED_INTEGRATION, NUMERICAL_INTEGRATION];
